### ISSUE TITLE
Hinawa can't find Apogee Duet FW unit

### ISSUE THREAD

**Issue by 777funk** [takaswie/hinawa-utils#11]
This is in Xubuntu 22.04. I can run the unit in Jack and it passes sound but Hinawa can't seem to load it.
Here is the command issued in the terminal:

$ hinawa-apogee-duet-cli 0 knob-states

Here is the error:

Traceback (most recent call last):
  File "/usr/bin/hinawa-apogee-duet-cli", line 6, in <module>
    from hinawa_utils.oxfw.apogee_duet_unit import ApogeeDuetUnit
  File "/usr/lib/python3/dist-packages/hinawa_utils/oxfw/apogee_duet_unit.py", line 6, in <module>
    from hinawa_utils.oxfw.apogee_protocol import (
  File "/usr/lib/python3/dist-packages/hinawa_utils/oxfw/apogee_protocol.py", line 141, in <module>
    class InputCmd():
  File "/usr/lib/python3/dist-packages/hinawa_utils/oxfw/apogee_protocol.py", line 274, in InputCmd
    def get_meters(cls, unit: Hinawa.FwUnit):
  File "/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Hinawa' object has no attribute 'FwUnit'

**Comment by takaswie** [comment]
Hi @777funk,

Thanks for your report. The issue comes from loss of backward compatibility in libhinawa. I'm sorry but hinawa-utils is abandoned nowadays. I recommend to use snd-firewire-ctl-service instead since I actively develop and maintain it but it demands you to install some system libraries. See https://lore.kernel.org/alsa-devel/20230419084401.GA659018@workstation/

I'm sorry for your inconvenience.

**Comment by 777funk** [comment]
> Hi @777funk,
> 
> Thanks for your report. The issue comes from loss of backward compatibility in libhinawa. I'm sorry but hinawa-utils is abandoned nowadays. I recommend to use snd-firewire-ctl-service instead since I actively develop and maintain it but it demands you to install some system libraries. See https://lore.kernel.org/alsa-devel/20230419084401.GA659018@workstation/
> 
> I'm sorry for your inconvenience.

Thank you for the reply. Is there any kind of step by step on how to install this in Ubuntu? I looked on the internet a little but didn't find anything. The Read Me helps a little and I was able to install Rust and Cargo and even got some of it to build but was not able to get this to run. Are there instructions for install and usage?

**Comment by takaswie** [comment]
> Is there any kind of step by step on how to install this in Ubuntu? I looked on the internet a little but didn't find anything. The Read Me helps a little and I was able to install Rust and Cargo and even got some of it to build but was not able to get this to run. Are there instructions for install and usage?

The project is relatively new (started three years ago), so it is hard to find something related.

You need to install some system library. The issue posted in past will be helpful:
https://github.com/alsa-project/snd-firewire-ctl-services/issues/85#issuecomment-1186495172

Anyway, it is better to file the issue in https://github.com/alsa-project/snd-firewire-ctl-services/ instead of here so that user finds it.

**Comment by takaswie** [comment]
Let me close it since no reactions come.
