### ISSUE TITLE
MacOS port ?

### ISSUE THREAD

**Issue by Xample** [takaswie/hinawa-utils#6]
Hi, I am wondering how hard it would be to run the "hinawa-apogee-duet-cli" on MacOS.

Apogee is not supporting anymore the duet 1 (fw) this lead me search for an alternative. While the duet is working without any driver on mac os, there is no way / tool available to do custom tasks such as activating the phantom input (which is what I am trying to achieve).

I am a noob in python but I do have some understanding on how a driver is working, what would be the biggest challenge in making it work on mac os Catalina ?

**Comment by takaswie** [comment]
Hi,

Thanks your opinion, however the tools in this repository are specific to Linux operating system.

As you know, Apogee Duet FireWire and MacOS communicate via IEEE 1394 bus. The bus is
maintained by 1394 OHCI controller hardware in MacOs machine. Software should operate the
controller hardware to communicate to Apogee Duet FireWire. MacOS produces API for software
for such purpose, however it's not portable. Linux kernel also has such API but it's not portable as well.
As long as I know, there is no abstraction layer to wrap the difference of these API, and I have no
motivation to invent such abstraction layer. Thus the tools are specific to Linux.

If you would like to make your tool to operate your Apogee Duet FireWire, you need to do below items:

1. learn MacOS API to operate controller hardware
2. study protocol specification defined by 1394 Trading Association (1394TA)
3. study protocol specification defined by Apogee for Duet FireWire
4. implement your tool

You can find archive of specification defined by 1394TA in Internet Archive service:

 * https://web.archive.org/web/20210216003030/http://1394ta.org/specifications/

The specifications you need to read are:

 * AV/C Digital Interface Command Set General  Specification Version 4.2  (September 1, 2004)

I note that hinawa-utils will be going to be closed near future since another software is under development.

 * https://github.com/alsa-project/snd-firewire-ctl-services

The coverage of the new software is larger than hinawa-utils. You can read corresponding implementation in
`libs/oxfw/protocols/src/apogee.rs`.

Cheers.

**Comment by Xample** [comment]
Okay thank you for the clarification, to what I've seen the `hinawa-apogee-cli` is part of the `hinawa-utils` which are both made in python and should therefore be portable, however for the low level access to the IEEE 1394 they use the GObject (PyGObject) as a bridge to the `libhinawa` which is made in pure C and very specific to the linux environment (if I understand, this is the OS specific part of the project).

So, either a port of `libhinawa` should be done, considering the abstraction layer you describe (otherwise it would be rewriting a compatible `libhinawa` without any documented api ). An alternative could be to take the abstraction one level above, such as before the `PyGObject` (or a common interface between `PyGObject`and a new MacOS specific controller)

Or rewrite an entire new driver getting inspired by the [apogee's protocol](https://github.com/takaswie/hinawa-utils/blob/master/hinawa_utils/oxfw/apogee_protocol.py)

While the project sounds interesting, the official reason for Apogee to have dropped the firewire support is because apple itself dropped it in 2012 letting a buggy unmaintained driver behind them. I am afraid to put such amount of work taking the risk to have the same conclusion as the Apogee's team had (or was it a commercial decision ?)

In anyway, congratulation for what you did, I really mean it! 👍🏻
